export EDITOR=vim

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM=auto

export GPG_TTY=$(tty)

export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

source "$HOME/.cargo/env"
